### PR TITLE
All state in slideList and syntax update

### PR DESCRIPTION
**Pull request by matzimowski**
some changes according to:
https://facebook.github.io/react/docs/reusable-components.html#stateless-functions

### CODE REVIEW

**Comment by matzimowski** [comment]
@kdzwinel :monkey:

**Comment by matzimowski** [comment]
in the next pr i will move separated results.html into React app

**Comment by kdzwinel** [comment]
Nice! :+1:

**Comment by matzimowski** [comment]
:+1:

**Pull request merged**
